# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_4sbWot6gHo9_MbX7mpMBqTo-K2RY1CP
"""

# Oddiy kalkulyator dasturi

def kalkulyator():
    print("Oddiy kalkulyator dasturiga xush kelibsiz!")
    print("Quyidagi amallardan birini tanlang:")
    print("1. Qo'shish (+)")
    print("2. Ayirish (-)")
    print("3. Ko'paytirish (*)")
    print("4. Bo'lish (/)")

    # Foydalanuvchidan amal tanlash
    amal = input("Amalni tanlang (1/2/3/4): ")

    if amal in ['1', '2', '3', '4']:
        # Foydalanuvchidan sonlarni kiritish
        try:
            son1 = float(input("Birinchi sonni kiriting: "))
            son2 = float(input("Ikkinchi sonni kiriting: "))
        except ValueError:
            print("Faqat son kiriting!")
            return

        # Tanlangan amalni bajarish
        if amal == '1':
            natija = son1 + son2
            print(f"{son1} + {son2} = {natija}")
        elif amal == '2':
            natija = son1 - son2
            print(f"{son1} - {son2} = {natija}")
        elif amal == '3':
            natija = son1 * son2
            print(f"{son1} * {son2} = {natija}")
        elif amal == '4':
            if son2 != 0:
                natija = son1 / son2
                print(f"{son1} / {son2} = {natija}")
            else:
                print("Nolga bo'lish mumkin emas!")
    else:
        print("Noto'g'ri amal tanlandi!")

# Kalkulyatorni ishga tushirish
kalkulyator()